[providers.node]
version = "18"

[phases]
[phases.install]
cmd = "npm install --legacy-peer-deps"

[phases.build]
cmd = "npm run build"

[start]
cmd = "npm run preview"

[variables]
NPM_CONFIG_PRODUCTION = "false"
NPM_CONFIG_INCLUDE = "dev"
NPM_CONFIG_LEGACY_PEER_DEPS = "true"
